/**
 * UI文言（多言語）— 全LP共通のシングルソース
 * ------------------------------------------------------------
 * 対応言語: en / zhs(簡体) / zht(繁体) / ko(韓国語) / id(インドネシア語)
 *
 * 【方針】
 *  ・ここに入っている英語原文は、すべて既存 store.njk / reserve-form-modal.njk に
 *    実在するコピーです。新しい訴求文言は追加していません。
 *  ・他言語はその英語原文の翻訳です。
 *  ・お客様の声(rev.*)は実際の投稿文のため、原文のまま全言語で表示します。
 *  ・{name} {city} {brand} {tel} は表示時にテンプレ側で置換されます。
 */

const EN = {
  // --- nav / common ---
  // --- theme (sushi / wagyu) 既存 store-sushi.njk / store-wagyu.njk より ---
  "hero.halal": "Halal Omakase Experience",
  "hero.tour": "Gastronomic Tour of Japan",
  "theme.sushi": "Sushi",
  "theme.wagyu": "Wagyu",
  "menu.chefs": "Chef's Omakase",
  "menu.sushiH": "Sushi Omakase Course",
  "menu.wagyuH": "Wagyu Omakase Course",
  "menu.sushiP": "Authentic sushi, crafted piece by piece and served Muslim-friendly — a quiet journey through the season's finest fish.",
  "menu.wagyuP": "Premium wagyu & Kobe beef, prepared course by course and served Muslim-friendly — sukiyaki, steak, and wagyu sushi.",
  "menu.follows": "Our omakase follows the season — ingredients may vary.",
  "reserve.btnSushi": "Reserve Your Sushi Omakase",
  "reserve.btnWagyu": "Reserve Your Wagyu Omakase",
  "tag.popular": "Most Popular",
  "nav.experience": "The Experience",
  "nav.menu": "Menu",
  "nav.story": "Our Story",
  "nav.halal": "Muslim-Friendly",
  "nav.access": "Access",
  "nav.interior": "Interior",
  "nav.performance": "Performance",
  "ui.slide": "Slide",
  "ui.googleReviews": "Google reviews",
  "ui.seeReviews": "See reviews on Google",
  "ui.outOf5": "out of 5",
  "nav.reserve": "Reserve",
  "ui.language": "Language",
  "lang.h": "Language",
  "lang.p": "The menu and information are the same in every language.",
  "ui.viewMore": "View more",
  "ui.viewLess": "Close",
  "ui.close": "Close",
  "ui.menu": "Menu",
  "ui.reviews": "reviews",

  // --- hero (既存: "Gastronomic Tour of JAPAN" / "Sushi & Wagyu Halal Omakase Experience") ---
  "hero.h1a": "Gastronomic Tour",
  "hero.h1b": "of JAPAN",
  "hero.sub": "Sushi & Wagyu Halal Omakase Experience",

  // --- the experience ---
  "exp.label": "The Experience",
  "exp.h": "A Journey Through Japan",
  "exp.p": "A journey through Japan's food culture — wagyu, sushi, and projection-mapped dining. Muslim-friendly omakase, crafted for travelers from around the world.",
  "exp.pm.h": "Sushi & Wagyu Course × Projection Mapping",
  "exp.pm.p": "Not just a meal — a journey through Japan. Each course unfolds alongside a projection-mapped experience of Japanese culture and travel, inviting you to savor Japan's culinary culture through exquisite dishes (all halal).",

  // --- menu ---
  "menu.label": "Course Selection",
  "menu.h": "Omakase Course Experience",
  "menu.note": "All Muslim-friendly · Seasonal menu",
  "menu.season": "* Ingredients may vary depending on the season.",
  "menu.premiumH": "\u201CSushi & Wagyu Indulgence\u201D",
  "menu.premiumP": "Within our signature courses, you'll also find premium dishes — crafted with the finest seasonal ingredients for an extraordinary experience.",
  "course.details": "See details",
  "course.reserve": "Reserve this course",
  "course.incl": "incl. tax",
  "tag.lunch": "Lunch only",
  "tag.recommended": "Recommended",

  // --- our story ---
  "story.label": "Our Story",
  "story.h": "The Story Begins in 1962",
  "story.p1": "The first generation started this journey as a Wagyu merchant. A craftsman who faced cattle, discerned the quality of meat, and honed his skills. Since then, the family business expanded to meat wholesale, butcher shops, and the food industry. I was raised alongside meat as the fifth generation.",
  "story.quote": "Wagyu was never a \u2018special occasion treat\u2019 for me. I have known its taste since I was a child and it was always close to me.",
  "story.by": "— 5th Generation Owner",
  "story.t.label": "The Turning Point",
  "story.t.p1": "However, in my 30s, when I visited America, that feeling was greatly shaken. The \u201CWAGYU\u201D I encountered there was completely different from the Wagyu I knew. Cattle from Australia and America were circulated as \u201CWagyu,\u201D and many people smiled as they ate, saying, \u201CIs this Wagyu?\u201D",
  "story.t.p2": "Seeing that scene brought me both surprise and frustration. As the fifth generation, I decided to deliver the \u201Creal Wagyu\u201D to the world once again — and opened this restaurant in the heart of Tokyo.",
  "story.q.label": "Our Commitment to Quality",
  "story.q.p": "I visit livestock farms all over Japan and purchase only Wagyu that I truly accept by the whole head. Not the industrially fattened Wagyu with excessive fat — rather, Wagyu raised healthily with umami and tenderness in the meat itself, not just in the fat. This philosophy carries through every dish we serve.",
  "story.w.label": "For Everyone in the World",
  "story.w.p": "I personally select Wagyu processed at trusted suppliers in Japan. This restaurant was born to share authentic Japanese food culture with everyone — regardless of nationality, religion, age, or gender.",

  // --- muslim-friendly ---
  "halal.label": "Muslim-Friendly Dining",
  "halal.h": "A Muslim-Friendly Dining Experience in {city}",
  "halal.p1": "Welcome to our restaurant — a warm, inclusive space where guests from all cultures can dine with peace of mind. We thoughtfully prepare pork-free, alcohol-free dishes, making us a trusted choice for Muslim travelers and families visiting Japan.",
  "halal.p2": "Please feel free to share any dietary preferences or restrictions when making your reservation — we will do our best to accommodate.",
  "badge.nopork": "No pork",
  "badge.noalc": "No alcohol in food",
  "badge.mf": "Muslim-friendly",

  // --- guest voices ---
  "voices.label": "Guest Voices",
  "voices.h": "From Around the World",
  "voices.p": "A selection of impressions shared by our guests.",

  // --- access ---
  "access.label": "Access",
  "access.h": "Find Us",
  "access.name": "Restaurant",
  "access.addr": "Address",
  "access.hours": "Hours",
  "access.open": "Open",
  "access.tel": "Tel",
  "access.stations": "Nearest station",
  "access.min": "min",
  "access.maps": "Open in Google Maps",

  // --- reserve ---
  "reserve.label": "Reserve",
  "reserve.h": "Begin Your Experience",
  "reserve.p": "Reservations recommended 2 weeks in advance. Walk-ins welcome subject to availability.",
  "reserve.btn": "Reserve your seat",
  "reserve.btnTc": "Reserve on TableCheck",
  "reserve.noteForm": "* Reservation is confirmed after email from {brand}.",
  "reserve.noteTc": "* Reservation handled by TableCheck — secure & instant.",
  "reserve.notePhone": "* Phone reservation only — please call us directly.",
  "reserve.tel": "Prefer to call?",

  // --- reservation form (partial: reserve-v2.njk) ---
  "rv.eyebrow": "Reservation",
  "rv.title": "Reservation Request",
  "rv.sub": "Reservation is confirmed after email from {brand}.",
  "rv.s1": "Date & time",
  "rv.s2": "Course",
  "rv.s3": "Your details",
  "rv.date": "Preferred date",
  "rv.time": "Time",
  "rv.guests": "Guests",
  "rv.course": "Course",
  "rv.coursePick": "Select a course",
  "rv.courseHint": "Prices are per person. All Muslim-friendly · Seasonal menu.",
  "rv.name": "Name",
  "rv.email": "Email",
  "rv.phone": "Phone",
  "rv.ref": "Referred by",
  "rv.optional": "Optional",
  "rv.msg": "Special requests",
  "rv.msgPh": "Allergies, dietary requirements, special occasions...",
  "rv.sameday": "Same-day? Call us",
  "rv.next": "Review & send",
  "rv.okTitle": "Request received",
  "rv.okBody": "Please wait for a confirmation from {brand}.",
  "rv.close": "Close",
  "rv.finalEyebrow": "Final check",
  "rv.finalTitle": "Please confirm your reservation",
  "rv.finalSub": "We prepare ingredients and seating based on your reservation. Please confirm details are correct.",
  "rv.date2": "Date",
  "rv.time2": "Time",
  "rv.guests2": "Guests",
  "rv.course2": "Course",
  "rv.cxTitle": "Cancellation Policy",
  "rv.cx48": "Within 48 hours: ¥5,000 / person",
  "rv.cx24": "Within 24 hours: ¥10,000 / person",
  "rv.cxTel": "For urgent inquiries, please call us at",
  "rv.pvTitle": "Privacy Policy",
  "rv.pvBody": "Personal information you provide (name, email, phone number, etc.) will be used solely for reservation confirmation, communication, and store notifications. We will not share your information with third parties except as required by law.",
  "rv.ck1": "I have confirmed the date, time and number of guests are correct.",
  "rv.ck2": "I have read and agree to the cancellation policy.",
  "rv.edit": "Edit",
  "rv.send": "Confirm & send",
  "rv.sending": "Sending...",
  "rv.eRequired": "Please fill in required fields.",
  "rv.ePast": "Please choose today or a future date.",
  "rv.eSameday": "For same-day reservations, please call us",
  "rv.ePassed": "This time slot has closed for today. Please choose another time or date.",
  "rv.eBlocked": "The selected date is unavailable. Please choose another date.",
  "rv.eCheck": "Please check both boxes.",
  "rv.eFull": "This time slot is fully booked. Please choose another time.",
  "rv.eNet": "Could not check availability. Please check your connection and try again.",
  "rv.eGeneric": "An error occurred. Please try again.",
  "rv.closedSlot": " (closed)",
  "rv.fullSlot": " (full)"
};

const JA = {
  "nav.experience": "体験", "nav.menu": "お品書き", "nav.story": "私たちの物語",
  "nav.halal": "ムスリムフレンドリー", "nav.access": "アクセス", "nav.reserve": "ご予約",
  "nav.interior": "店内", "nav.performance": "パフォーマンス",
  "ui.language": "言語", "lang.h": "言語", "lang.p": "どの言語でもお品書きと情報は同じです。",
  "ui.viewMore": "詳しく見る", "ui.viewLess": "閉じる", "ui.close": "閉じる", "ui.menu": "メニュー",
  "ui.reviews": "件のクチコミ", "ui.slide": "スライド",
  "ui.googleReviews": "Google クチコミ", "ui.seeReviews": "Google でクチコミを見る", "ui.outOf5": "5点満点中",
  "hero.h1a": "Gastronomic Tour", "hero.h1b": "of JAPAN",
  "hero.sub": "寿司と和牛のハラル Omakase 体験",
  "hero.halal": "ハラル Omakase 体験", "hero.tour": "日本の美食をめぐる旅",
  "theme.sushi": "寿司", "theme.wagyu": "和牛",
  "exp.label": "体験", "exp.h": "日本をめぐる旅",
  "exp.p": "和牛、寿司、そしてプロジェクションマッピング。日本の食文化をめぐる旅です。世界中からお越しになる方のために整えた、ムスリムフレンドリーの omakase。",
  "exp.pm.h": "寿司と和牛のコース × プロジェクションマッピング",
  "exp.pm.p": "ただの食事ではなく、日本をめぐる旅。一皿ごとに、日本の文化と旅を映すプロジェクションマッピングが展開します。精緻な料理を通して、日本の食文化を味わってください（全品ハラル）。",
  "menu.label": "コースのご案内", "menu.h": "Omakase コース体験",
  "menu.note": "全品ムスリムフレンドリー・季節のお品書き",
  "menu.season": "※ 食材は季節により変わることがございます。",
  "menu.premiumH": "「寿司と和牛の贅」",
  "menu.premiumP": "看板コースの中には、最上の季節の食材で仕立てたプレミアムの一皿もご用意しています。",
  "menu.chefs": "板前のおまかせ",
  "menu.sushiH": "寿司 Omakase コース", "menu.wagyuH": "和牛 Omakase コース",
  "menu.sushiP": "本格の寿司を一貫ずつ、ムスリムフレンドリーで。季節の魚を静かにたどる旅です。",
  "menu.wagyuP": "上質な和牛と神戸牛を一品ずつ、ムスリムフレンドリーで。すき焼き、ステーキ、そして和牛寿司。",
  "menu.follows": "おまかせは季節に従います。食材は変わることがございます。",
  "course.details": "詳細を見る", "course.reserve": "このコースを予約する", "course.incl": "税込",
  "tag.lunch": "昼のみ", "tag.recommended": "おすすめ", "tag.popular": "一番人気",
  "story.label": "私たちの物語", "story.h": "物語は 1962 年に始まりました",
  "story.p1": "初代は和牛の商人としてこの道を歩み始めました。牛と向き合い、肉の善し悪しを見極め、腕を磨いた職人でした。以来、家業は食肉卸、精肉店、そして飲食業へと広がりました。五代目である私は、肉とともに育ちました。",
  "story.quote": "私にとって和牛は「特別な日のごちそう」ではありませんでした。子どもの頃からその味を知っていて、いつもそばにありました。",
  "story.by": "— 五代目店主",
  "story.t.label": "転機",
  "story.t.p1": "しかし三十代でアメリカを訪れたとき、その感覚は大きく揺さぶられました。そこで出会った「WAGYU」は、私の知る和牛とはまったく別のものでした。オーストラリアやアメリカの牛が「和牛」として流通し、多くの人が「これが和牛か」と笑顔で口にしていたのです。",
  "story.t.p2": "その光景に、驚きと悔しさを覚えました。五代目として、もう一度「本物の和牛」を世界へ届けようと決め、東京の中心にこの店を開きました。",
  "story.q.label": "品質へのこだわり",
  "story.q.p": "日本各地の畜産農家を訪ね、自分が心から納得した和牛だけを一頭単位で仕入れています。脂を過剰につけた工業的な肥育ではなく、健やかに育ち、脂だけでなく肉そのものに旨みと柔らかさを備えた和牛です。この考えは、お出しするすべての料理に通じています。",
  "story.w.label": "世界のすべての方へ",
  "story.w.p": "日本の信頼できる加工先で処理された和牛を、私自身が選んでいます。この店は、国籍・宗教・年齢・性別を問わず、すべての方と本物の日本の食文化を分かち合うために生まれました。",
  "halal.label": "ムスリムフレンドリーのお食事",
  "halal.h": "{city}のムスリムフレンドリーなお食事体験",
  "halal.p1": "当店へようこそ。あらゆる文化のお客様が安心して食事を楽しめる、あたたかく開かれた空間です。豚肉不使用・アルコール不使用の料理を丁寧にご用意し、日本を訪れるムスリムの旅行者やご家族に選ばれています。",
  "halal.p2": "ご予約の際に、お食事の好みや制限をお気軽にお知らせください。できる限り対応いたします。",
  "badge.nopork": "豚肉不使用", "badge.noalc": "料理にアルコール不使用", "badge.mf": "ムスリムフレンドリー",
  "voices.label": "お客様の声", "voices.h": "世界各地から",
  "voices.p": "お客様からいただいた感想の一部です。",
  "access.label": "アクセス", "access.h": "店舗のご案内", "access.name": "店名", "access.addr": "住所",
  "access.hours": "営業時間", "access.open": "営業", "access.tel": "電話",
  "access.stations": "最寄駅", "access.min": "分", "access.maps": "Google マップで開く",
  "reserve.label": "ご予約", "reserve.h": "体験を始める",
  "reserve.p": "2週間前までのご予約をおすすめします。当日のご来店も、空席がございましたら承ります。",
  "reserve.btn": "席を予約する", "reserve.btnTc": "TableCheck で予約する",
  "reserve.btnSushi": "寿司 Omakase を予約する", "reserve.btnWagyu": "和牛 Omakase を予約する",
  "reserve.noteForm": "※ ご予約は {brand} からのメール送信をもって確定します。",
  "reserve.noteTc": "※ ご予約は TableCheck で安全・即時に承ります。",
  "reserve.notePhone": "※ お電話のみの受付です。店舗まで直接ご連絡ください。",
  "reserve.tel": "お電話でのご予約は",
  "rv.eyebrow": "ご予約", "rv.title": "ご予約リクエスト",
  "rv.sub": "ご予約は {brand} からのメール送信をもって確定します。",
  "rv.s1": "日付と時間", "rv.s2": "コース", "rv.s3": "お客様情報",
  "rv.date": "ご希望日", "rv.time": "時間", "rv.guests": "人数", "rv.course": "コース",
  "rv.coursePick": "コースをお選びください",
  "rv.courseHint": "価格は1名様あたりです。全品ムスリムフレンドリー・季節のお品書き。",
  "rv.name": "お名前", "rv.email": "メールアドレス", "rv.phone": "電話番号", "rv.ref": "ご紹介者",
  "rv.optional": "任意", "rv.msg": "ご要望", "rv.msgPh": "アレルギー、食事制限、記念日など…",
  "rv.sameday": "当日のご予約はお電話で", "rv.next": "内容を確認する",
  "rv.okTitle": "リクエストを承りました", "rv.okBody": "{brand} からの確認のご連絡をお待ちください。",
  "rv.close": "閉じる", "rv.finalEyebrow": "最終確認", "rv.finalTitle": "ご予約内容をご確認ください",
  "rv.finalSub": "ご予約に合わせて食材とお席をご用意します。内容に誤りがないかご確認ください。",
  "rv.date2": "日付", "rv.time2": "時間", "rv.guests2": "人数", "rv.course2": "コース",
  "rv.cxTitle": "キャンセルポリシー",
  "rv.cx48": "48時間前以内：1名様 ¥5,000", "rv.cx24": "24時間前以内：1名様 ¥10,000",
  "rv.cxTel": "お急ぎのご連絡はこちらまで", "rv.pvTitle": "個人情報の取り扱い",
  "rv.pvBody": "ご記入いただいた個人情報（お名前、メールアドレス、電話番号等）は、ご予約の確認・ご連絡・店舗からのご案内にのみ使用します。法令に基づく場合を除き、第三者に提供することはありません。",
  "rv.ck1": "日付・時間・人数に誤りがないことを確認しました。",
  "rv.ck2": "キャンセルポリシーを読み、同意します。",
  "rv.edit": "修正する", "rv.send": "確認して送信", "rv.sending": "送信中…",
  "rv.eRequired": "必須項目をご入力ください。",
  "rv.ePast": "本日以降の日付をお選びください。",
  "rv.eSameday": "当日のご予約はお電話で承ります",
  "rv.ePassed": "本日のこの時間枠は受付を終了しました。別の時間または日付をお選びください。",
  "rv.eBlocked": "選択された日は受付しておりません。別の日をお選びください。",
  "rv.eCheck": "両方にチェックを入れてください。",
  "rv.eFull": "この時間枠は満席です。別の時間をお選びください。",
  "rv.eNet": "空き状況の確認に失敗しました。通信環境をご確認のうえ、もう一度お試しください。",
  "rv.eGeneric": "エラーが発生しました。もう一度お試しください。",
  "rv.closedSlot": "（受付終了）", "rv.fullSlot": "（満席）"
};

const ZHS = {
  "hero.halal": "清真 Omakase 体验", "hero.tour": "日本美食之旅",
  "theme.sushi": "寿司", "theme.wagyu": "和牛",
  "menu.chefs": "师傅的 Omakase",
  "menu.sushiH": "寿司 Omakase 套餐", "menu.wagyuH": "和牛 Omakase 套餐",
  "menu.sushiP": "道地的寿司，逐贯捏制、穆斯林友善——一场穿越当季上乘鱼货的静谧旅程。",
  "menu.wagyuP": "顶级和牛与神户牛，逐道呈上、穆斯林友善——寿喜烧、牛排与和牛寿司。",
  "menu.follows": "我们的 omakase 顺应季节，食材可能有所变动。",
  "reserve.btnSushi": "预约寿司 Omakase", "reserve.btnWagyu": "预约和牛 Omakase",
  "tag.popular": "最受欢迎",
  "nav.experience": "用餐体验", "nav.menu": "菜单", "nav.story": "品牌故事",
  "nav.halal": "穆斯林友善", "nav.access": "交通方式", "nav.reserve": "预约", "nav.interior": "店内", "nav.performance": "现场演出", "ui.slide": "幻灯片", "ui.googleReviews": "Google 评价", "ui.seeReviews": "在 Google 查看评价", "ui.outOf5": "满分 5 分",
  "ui.language": "语言", "lang.h": "语言", "lang.p": "各语言的菜单与资讯完全相同。", "ui.viewMore": "查看更多", "ui.viewLess": "收起", "ui.close": "关闭",
  "ui.menu": "选单", "ui.reviews": "则评价",
  "hero.h1a": "日本美食之旅", "hero.h1b": "GASTRONOMIC TOUR OF JAPAN",
  "hero.sub": "寿司与和牛 清真 Omakase 体验",
  "exp.label": "用餐体验", "exp.h": "一场穿越日本的旅程",
  "exp.p": "一场穿越日本饮食文化的旅程——和牛、寿司，以及投影映射餐飨。为来自世界各地的旅人打造的穆斯林友善 omakase。",
  "exp.pm.h": "寿司与和牛套餐 × 投影映射",
  "exp.pm.p": "不只是一顿饭，而是一场穿越日本的旅程。每一道菜与日本文化及旅行的投影映射体验同步展开，邀您透过精致料理品味日本饮食文化（全部为清真）。",
  "menu.label": "套餐选择", "menu.h": "Omakase 套餐体验",
  "menu.note": "全部穆斯林友善 · 时令菜单", "menu.season": "※ 食材依季节可能有所变动。",
  "menu.premiumH": "「寿司与和牛的极致享受」",
  "menu.premiumP": "在我们的招牌套餐中，还能找到以最上乘时令食材制作的尊享料理，带来非凡体验。",
  "course.details": "查看详情", "course.reserve": "预约此套餐", "course.incl": "含税", "tag.lunch": "仅限午间", "tag.recommended": "推荐",
  "story.label": "品牌故事", "story.h": "故事始于 1962 年",
  "story.p1": "第一代以和牛商人的身分踏上这段旅程。他面对牛只、辨别肉质、磨练手艺。此后家业扩展至肉品批发、精肉店与餐饮业。身为第五代，我是与肉一同长大的。",
  "story.quote": "对我而言，和牛从来不是「特别的日子才吃的东西」。它的味道从我小时候就熟悉，一直近在身边。",
  "story.by": "— 第五代经营者",
  "story.t.label": "转折点",
  "story.t.p1": "然而在我三十多岁造访美国时，这份心情受到极大冲击。我在那里遇到的「WAGYU」，与我所认识的和牛完全不同。来自澳洲与美国的牛只以「和牛」之名流通，许多人一边吃一边笑着说：「这就是和牛吗？」",
  "story.t.p2": "看到那一幕，我既惊讶又不甘。身为第五代，我决定再一次将「真正的和牛」送到世界面前——于是在东京中心开了这家餐厅。",
  "story.q.label": "我们对品质的坚持",
  "story.q.p": "我走访日本各地的畜牧农场，只以整头为单位采购自己真正认可的和牛。不是脂肪过多、工业化育肥的和牛，而是健康饲养、肉本身就带有鲜味与柔嫩度的和牛。这份理念贯穿我们供应的每一道菜。",
  "story.w.label": "献给世界上的每一个人",
  "story.w.p": "我亲自挑选在日本值得信赖的供应商处加工的和牛。这家餐厅的诞生，是为了与所有人分享道地的日本饮食文化——无论国籍、宗教、年龄或性别。",
  "halal.label": "穆斯林友善餐饮", "halal.h": "{city}的穆斯林友善用餐体验",
  "halal.p1": "欢迎光临本店——这是一个温暖而包容的空间，让来自各种文化的宾客都能安心用餐。我们用心准备不含猪肉、不含酒精的料理，成为造访日本的穆斯林旅客与家庭值得信赖的选择。",
  "halal.p2": "预约时欢迎告知任何饮食偏好或限制，我们会尽力配合。",
  "badge.nopork": "不含猪肉", "badge.noalc": "料理不含酒精", "badge.mf": "穆斯林友善",
  "voices.label": "顾客评价", "voices.h": "来自世界各地", "voices.p": "以下是宾客分享的部分感想。",
  "access.label": "交通方式", "access.h": "如何前往", "access.name": "店名", "access.addr": "地址",
  "access.hours": "营业时间", "access.open": "营业", "access.tel": "电话",
  "access.stations": "最近车站", "access.min": "分钟", "access.maps": "在 Google 地图开启",
  "reserve.label": "预约", "reserve.h": "开启您的体验",
  "reserve.p": "建议提前两周预约。现场候位视空位情况欢迎光临。",
  "reserve.btn": "预约座位", "reserve.btnTc": "透过 TableCheck 预约",
  "reserve.noteForm": "※ 预约在收到 {brand} 的邮件后确认成立。",
  "reserve.noteTc": "※ 预约由 TableCheck 处理，安全且即时。",
  "reserve.notePhone": "※ 仅接受电话预约，请直接来电。",
  "reserve.tel": "想以电话预约？",
  "rv.eyebrow": "预约", "rv.title": "预约申请",
  "rv.sub": "预约在收到 {brand} 的邮件后确认成立。",
  "rv.s1": "日期与时间", "rv.s2": "套餐", "rv.s3": "您的资料",
  "rv.date": "希望日期", "rv.time": "时间", "rv.guests": "人数", "rv.course": "套餐",
  "rv.coursePick": "请选择套餐", "rv.courseHint": "价格为每位。全部穆斯林友善 · 时令菜单。",
  "rv.name": "姓名", "rv.email": "电子邮件", "rv.phone": "电话", "rv.ref": "介绍人",
  "rv.optional": "选填", "rv.msg": "特殊需求", "rv.msgPh": "过敏、饮食限制、纪念日等…",
  "rv.sameday": "当日预约请来电", "rv.next": "确认内容",
  "rv.okTitle": "已收到您的预约申请", "rv.okBody": "请等候 {brand} 的确认邮件。",
  "rv.close": "关闭", "rv.finalEyebrow": "最终确认", "rv.finalTitle": "请确认您的预约内容",
  "rv.finalSub": "我们会依预约准备食材与座位，请确认内容无误。",
  "rv.date2": "日期", "rv.time2": "时间", "rv.guests2": "人数", "rv.course2": "套餐",
  "rv.cxTitle": "取消规定", "rv.cx48": "48小时内：每位 ¥5,000", "rv.cx24": "24小时内：每位 ¥10,000",
  "rv.cxTel": "紧急事宜请来电", "rv.pvTitle": "隐私政策",
  "rv.pvBody": "您提供的个人资料（姓名、邮件、电话等）仅用于预约确认、联络与店铺通知。除法律要求外，我们不会提供给第三方。",
  "rv.ck1": "我已确认日期、时间与人数无误。", "rv.ck2": "我已阅读并同意取消规定。",
  "rv.edit": "修改", "rv.send": "确认并送出", "rv.sending": "传送中…",
  "rv.eRequired": "请填写必填项目。", "rv.ePast": "请选择今天或之后的日期。",
  "rv.eSameday": "当日预约请来电洽询", "rv.ePassed": "今日该时段已截止，请选择其他时间或日期。",
  "rv.eBlocked": "所选日期无法预约，请选择其他日期。", "rv.eCheck": "请勾选两个项目。",
  "rv.eFull": "该时段已满席，请选择其他时间。",
  "rv.eNet": "无法确认空位状况，请检查网路后再试。", "rv.eGeneric": "发生错误，请再试一次。",
  "rv.closedSlot": "（已截止）", "rv.fullSlot": "（满席）"
};

const ZHT = {
  "hero.halal": "清真 Omakase 體驗", "hero.tour": "日本美食之旅",
  "theme.sushi": "壽司", "theme.wagyu": "和牛",
  "menu.chefs": "師傅的 Omakase",
  "menu.sushiH": "壽司 Omakase 套餐", "menu.wagyuH": "和牛 Omakase 套餐",
  "menu.sushiP": "道地的壽司，逐貫捏製、穆斯林友善——一場穿越當季上乘魚貨的靜謐旅程。",
  "menu.wagyuP": "頂級和牛與神戶牛，逐道呈上、穆斯林友善——壽喜燒、牛排與和牛壽司。",
  "menu.follows": "我們的 omakase 順應季節，食材可能有所變動。",
  "reserve.btnSushi": "預約壽司 Omakase", "reserve.btnWagyu": "預約和牛 Omakase",
  "tag.popular": "最受歡迎",
  "nav.experience": "用餐體驗", "nav.menu": "菜單", "nav.story": "品牌故事",
  "nav.halal": "穆斯林友善", "nav.access": "交通方式", "nav.reserve": "預約", "nav.interior": "店內", "nav.performance": "現場演出", "ui.slide": "幻燈片", "ui.googleReviews": "Google 評價", "ui.seeReviews": "在 Google 查看評價", "ui.outOf5": "滿分 5 分",
  "ui.language": "語言", "lang.h": "語言", "lang.p": "各語言的菜單與資訊完全相同。", "ui.viewMore": "查看更多", "ui.viewLess": "收合", "ui.close": "關閉",
  "ui.menu": "選單", "ui.reviews": "則評價",
  "hero.h1a": "日本美食之旅", "hero.h1b": "GASTRONOMIC TOUR OF JAPAN",
  "hero.sub": "壽司與和牛 清真 Omakase 體驗",
  "exp.label": "用餐體驗", "exp.h": "一場穿越日本的旅程",
  "exp.p": "一場穿越日本飲食文化的旅程——和牛、壽司，以及投影映射餐饗。為來自世界各地的旅人打造的穆斯林友善 omakase。",
  "exp.pm.h": "壽司與和牛套餐 × 投影映射",
  "exp.pm.p": "不只是一頓飯，而是一場穿越日本的旅程。每一道菜與日本文化及旅行的投影映射體驗同步展開，邀您透過精緻料理品味日本飲食文化（全部為清真）。",
  "menu.label": "套餐選擇", "menu.h": "Omakase 套餐體驗",
  "menu.note": "全部穆斯林友善 · 時令菜單", "menu.season": "※ 食材依季節可能有所變動。",
  "menu.premiumH": "「壽司與和牛的極致享受」",
  "menu.premiumP": "在我們的招牌套餐中，還能找到以最上乘時令食材製作的尊享料理，帶來非凡體驗。",
  "course.details": "查看詳情", "course.reserve": "預約此套餐", "course.incl": "含稅", "tag.lunch": "僅限午間", "tag.recommended": "推薦",
  "story.label": "品牌故事", "story.h": "故事始於 1962 年",
  "story.p1": "第一代以和牛商人的身分踏上這段旅程。他面對牛隻、辨別肉質、磨練手藝。此後家業擴展至肉品批發、精肉店與餐飲業。身為第五代，我是與肉一同長大的。",
  "story.quote": "對我而言，和牛從來不是「特別的日子才吃的東西」。它的味道從我小時候就熟悉，一直近在身邊。",
  "story.by": "— 第五代經營者",
  "story.t.label": "轉折點",
  "story.t.p1": "然而在我三十多歲造訪美國時，這份心情受到極大衝擊。我在那裡遇到的「WAGYU」，與我所認識的和牛完全不同。來自澳洲與美國的牛隻以「和牛」之名流通，許多人一邊吃一邊笑著說：「這就是和牛嗎？」",
  "story.t.p2": "看到那一幕，我既驚訝又不甘。身為第五代，我決定再一次將「真正的和牛」送到世界面前——於是在東京中心開了這家餐廳。",
  "story.q.label": "我們對品質的堅持",
  "story.q.p": "我走訪日本各地的畜牧農場，只以整頭為單位採購自己真正認可的和牛。不是脂肪過多、工業化育肥的和牛，而是健康飼養、肉本身就帶有鮮味與柔嫩度的和牛。這份理念貫穿我們供應的每一道菜。",
  "story.w.label": "獻給世界上的每一個人",
  "story.w.p": "我親自挑選在日本值得信賴的供應商處加工的和牛。這家餐廳的誕生，是為了與所有人分享道地的日本飲食文化——無論國籍、宗教、年齡或性別。",
  "halal.label": "穆斯林友善餐飲", "halal.h": "{city}的穆斯林友善用餐體驗",
  "halal.p1": "歡迎光臨本店——這是一個溫暖而包容的空間，讓來自各種文化的賓客都能安心用餐。我們用心準備不含豬肉、不含酒精的料理，成為造訪日本的穆斯林旅客與家庭值得信賴的選擇。",
  "halal.p2": "預約時歡迎告知任何飲食偏好或限制，我們會盡力配合。",
  "badge.nopork": "不含豬肉", "badge.noalc": "料理不含酒精", "badge.mf": "穆斯林友善",
  "voices.label": "顧客評價", "voices.h": "來自世界各地", "voices.p": "以下是賓客分享的部分感想。",
  "access.label": "交通方式", "access.h": "如何前往", "access.name": "店名", "access.addr": "地址",
  "access.hours": "營業時間", "access.open": "營業", "access.tel": "電話",
  "access.stations": "最近車站", "access.min": "分鐘", "access.maps": "在 Google 地圖開啟",
  "reserve.label": "預約", "reserve.h": "開啟您的體驗",
  "reserve.p": "建議提前兩週預約。現場候位視空位情況歡迎光臨。",
  "reserve.btn": "預約座位", "reserve.btnTc": "透過 TableCheck 預約",
  "reserve.noteForm": "※ 預約在收到 {brand} 的郵件後確認成立。",
  "reserve.noteTc": "※ 預約由 TableCheck 處理，安全且即時。",
  "reserve.notePhone": "※ 僅接受電話預約，請直接來電。",
  "reserve.tel": "想以電話預約？",
  "rv.eyebrow": "預約", "rv.title": "預約申請",
  "rv.sub": "預約在收到 {brand} 的郵件後確認成立。",
  "rv.s1": "日期與時間", "rv.s2": "套餐", "rv.s3": "您的資料",
  "rv.date": "希望日期", "rv.time": "時間", "rv.guests": "人數", "rv.course": "套餐",
  "rv.coursePick": "請選擇套餐", "rv.courseHint": "價格為每位。全部穆斯林友善 · 時令菜單。",
  "rv.name": "姓名", "rv.email": "電子郵件", "rv.phone": "電話", "rv.ref": "介紹人",
  "rv.optional": "選填", "rv.msg": "特殊需求", "rv.msgPh": "過敏、飲食限制、紀念日等…",
  "rv.sameday": "當日預約請來電", "rv.next": "確認內容",
  "rv.okTitle": "已收到您的預約申請", "rv.okBody": "請等候 {brand} 的確認郵件。",
  "rv.close": "關閉", "rv.finalEyebrow": "最終確認", "rv.finalTitle": "請確認您的預約內容",
  "rv.finalSub": "我們會依預約準備食材與座位，請確認內容無誤。",
  "rv.date2": "日期", "rv.time2": "時間", "rv.guests2": "人數", "rv.course2": "套餐",
  "rv.cxTitle": "取消規定", "rv.cx48": "48小時內：每位 ¥5,000", "rv.cx24": "24小時內：每位 ¥10,000",
  "rv.cxTel": "緊急事宜請來電", "rv.pvTitle": "隱私政策",
  "rv.pvBody": "您提供的個人資料（姓名、郵件、電話等）僅用於預約確認、聯絡與店鋪通知。除法律要求外，我們不會提供給第三方。",
  "rv.ck1": "我已確認日期、時間與人數無誤。", "rv.ck2": "我已閱讀並同意取消規定。",
  "rv.edit": "修改", "rv.send": "確認並送出", "rv.sending": "傳送中…",
  "rv.eRequired": "請填寫必填項目。", "rv.ePast": "請選擇今天或之後的日期。",
  "rv.eSameday": "當日預約請來電洽詢", "rv.ePassed": "今日該時段已截止，請選擇其他時間或日期。",
  "rv.eBlocked": "所選日期無法預約，請選擇其他日期。", "rv.eCheck": "請勾選兩個項目。",
  "rv.eFull": "該時段已滿席，請選擇其他時間。",
  "rv.eNet": "無法確認空位狀況，請檢查網路後再試。", "rv.eGeneric": "發生錯誤，請再試一次。",
  "rv.closedSlot": "（已截止）", "rv.fullSlot": "（滿席）"
};

const KO = {
  "hero.halal": "할랄 오마카세 경험", "hero.tour": "일본 미식 여행",
  "theme.sushi": "스시", "theme.wagyu": "와규",
  "menu.chefs": "셰프의 오마카세",
  "menu.sushiH": "스시 오마카세 코스", "menu.wagyuH": "와규 오마카세 코스",
  "menu.sushiP": "정통 스시를 한 점씩 쥐어 무슬림 프렌들리로 — 제철 최상급 생선을 따라가는 고요한 여정.",
  "menu.wagyuP": "프리미엄 와규와 고베규를 코스로, 무슬림 프렌들리로 — 스키야키, 스테이크, 와규 스시.",
  "menu.follows": "저희 오마카세는 계절을 따릅니다. 식재료는 달라질 수 있습니다.",
  "reserve.btnSushi": "스시 오마카세 예약", "reserve.btnWagyu": "와규 오마카세 예약",
  "tag.popular": "가장 인기",
  "nav.experience": "다이닝 경험", "nav.menu": "메뉴", "nav.story": "브랜드 스토리",
  "nav.halal": "무슬림 프렌들리", "nav.access": "오시는 길", "nav.reserve": "예약", "nav.interior": "매장 내부", "nav.performance": "퍼포먼스", "ui.slide": "슬라이드", "ui.googleReviews": "Google 리뷰", "ui.seeReviews": "Google에서 리뷰 보기", "ui.outOf5": "5점 만점",
  "ui.language": "언어", "lang.h": "언어", "lang.p": "어떤 언어에서도 메뉴와 정보는 동일합니다.", "ui.viewMore": "더 보기", "ui.viewLess": "닫기", "ui.close": "닫기",
  "ui.menu": "메뉴", "ui.reviews": "개의 리뷰",
  "hero.h1a": "일본 미식 여행", "hero.h1b": "GASTRONOMIC TOUR OF JAPAN",
  "hero.sub": "스시 & 와규 할랄 오마카세 경험",
  "exp.label": "다이닝 경험", "exp.h": "일본을 가로지르는 여정",
  "exp.p": "일본의 음식 문화를 가로지르는 여정 — 와규, 스시, 그리고 프로젝션 매핑 다이닝. 세계 각지에서 온 여행자를 위해 준비한 무슬림 프렌들리 오마카세입니다.",
  "exp.pm.h": "스시 & 와규 코스 × 프로젝션 매핑",
  "exp.pm.p": "단순한 식사가 아닌, 일본을 가로지르는 여정입니다. 각 코스는 일본의 문화와 여행을 담은 프로젝션 매핑과 함께 펼쳐지며, 정성스러운 요리를 통해 일본의 미식 문화를 음미하도록 초대합니다 (전 메뉴 할랄).",
  "menu.label": "코스 선택", "menu.h": "오마카세 코스 경험",
  "menu.note": "전 메뉴 무슬림 프렌들리 · 제철 메뉴", "menu.season": "※ 식재료는 계절에 따라 달라질 수 있습니다.",
  "menu.premiumH": "\u201C스시 & 와규의 탐닉\u201D",
  "menu.premiumP": "시그니처 코스 안에는 최상급 제철 식재료로 만든 프리미엄 요리도 준비되어 있어, 특별한 경험을 선사합니다.",
  "course.details": "상세 보기", "course.reserve": "이 코스로 예약", "course.incl": "세금 포함", "tag.lunch": "런치 전용", "tag.recommended": "추천",
  "story.label": "브랜드 스토리", "story.h": "1962년에 시작된 이야기",
  "story.p1": "1대는 와규 상인으로서 이 여정을 시작했습니다. 소를 마주하고 고기의 품질을 가려내며 기술을 갈고닦은 장인이었습니다. 이후 가업은 정육 도매, 정육점, 외식업으로 넓어졌습니다. 저는 5대째로서 고기와 함께 자랐습니다.",
  "story.quote": "저에게 와규는 결코 \u2018특별한 날에만 먹는 음식\u2019이 아니었습니다. 어린 시절부터 그 맛을 알고 있었고, 늘 가까이에 있었습니다.",
  "story.by": "— 5대째 오너",
  "story.t.label": "전환점",
  "story.t.p1": "그러나 30대에 미국을 방문했을 때 그 감각은 크게 흔들렸습니다. 그곳에서 만난 \u201CWAGYU\u201D는 제가 알던 와규와 전혀 달랐습니다. 호주와 미국의 소가 \u201C와규\u201D라는 이름으로 유통되었고, 많은 사람들이 \u201C이게 와규인가요?\u201D라며 웃으며 먹고 있었습니다.",
  "story.t.p2": "그 광경은 놀라움과 안타까움을 동시에 안겨 주었습니다. 5대째로서 저는 \u201C진짜 와규\u201D를 다시 한번 세계에 전하기로 결심했고, 도쿄 한복판에 이 가게를 열었습니다.",
  "story.q.label": "품질에 대한 고집",
  "story.q.p": "일본 각지의 축산 농가를 찾아다니며, 제가 진심으로 납득한 와규만을 한 마리 단위로 매입합니다. 지방이 과한 공업적 비육 와규가 아니라, 지방뿐 아니라 살코기 자체에 감칠맛과 부드러움을 지닌, 건강하게 자란 와규입니다. 이 철학은 저희가 내는 모든 요리에 이어집니다.",
  "story.w.label": "세계의 모든 분께",
  "story.w.p": "일본의 신뢰할 수 있는 가공처에서 처리된 와규를 제가 직접 고릅니다. 이 가게는 국적, 종교, 연령, 성별에 관계없이 모든 분과 진짜 일본의 음식 문화를 나누기 위해 태어났습니다.",
  "halal.label": "무슬림 프렌들리 다이닝", "halal.h": "{city}의 무슬림 프렌들리 다이닝",
  "halal.p1": "저희 가게에 오신 것을 환영합니다. 다양한 문화권의 손님이 안심하고 식사할 수 있는 따뜻하고 포용적인 공간입니다. 돼지고기와 알코올을 사용하지 않은 요리를 정성껏 준비하여, 일본을 찾는 무슬림 여행자와 가족분들이 믿고 선택할 수 있는 곳이 되고자 합니다.",
  "halal.p2": "예약 시 식사 취향이나 제한 사항을 편하게 알려 주세요. 최대한 맞춰 드리겠습니다.",
  "badge.nopork": "돼지고기 무사용", "badge.noalc": "요리에 알코올 무사용", "badge.mf": "무슬림 프렌들리",
  "voices.label": "고객 후기", "voices.h": "세계 각지에서", "voices.p": "손님들이 남겨 주신 감상 중 일부입니다.",
  "access.label": "오시는 길", "access.h": "찾아오시는 길", "access.name": "매장명", "access.addr": "주소",
  "access.hours": "영업시간", "access.open": "영업", "access.tel": "전화",
  "access.stations": "가까운 역", "access.min": "분", "access.maps": "Google 지도에서 열기",
  "reserve.label": "예약", "reserve.h": "경험을 시작하세요",
  "reserve.p": "2주 전 예약을 권장합니다. 워크인은 좌석 상황에 따라 안내해 드립니다.",
  "reserve.btn": "좌석 예약하기", "reserve.btnTc": "TableCheck에서 예약",
  "reserve.noteForm": "※ 예약은 {brand}의 메일 발송 후 확정됩니다.",
  "reserve.noteTc": "※ 예약은 TableCheck에서 안전하고 즉시 처리됩니다.",
  "reserve.notePhone": "※ 전화 예약만 가능합니다. 매장으로 직접 전화해 주세요.",
  "reserve.tel": "전화로 예약하시겠어요?",
  "rv.eyebrow": "예약", "rv.title": "예약 신청",
  "rv.sub": "예약은 {brand}의 메일 발송 후 확정됩니다.",
  "rv.s1": "날짜와 시간", "rv.s2": "코스", "rv.s3": "고객 정보",
  "rv.date": "희망 날짜", "rv.time": "시간", "rv.guests": "인원", "rv.course": "코스",
  "rv.coursePick": "코스를 선택하세요", "rv.courseHint": "가격은 1인 기준입니다. 전 메뉴 무슬림 프렌들리 · 제철 메뉴.",
  "rv.name": "이름", "rv.email": "이메일", "rv.phone": "전화번호", "rv.ref": "소개해 주신 분",
  "rv.optional": "선택", "rv.msg": "요청 사항", "rv.msgPh": "알레르기, 식이 제한, 기념일 등…",
  "rv.sameday": "당일 예약은 전화로", "rv.next": "내용 확인하기",
  "rv.okTitle": "예약 신청을 접수했습니다", "rv.okBody": "{brand}의 확인 메일을 기다려 주세요.",
  "rv.close": "닫기", "rv.finalEyebrow": "최종 확인", "rv.finalTitle": "예약 내용을 확인해 주세요",
  "rv.finalSub": "예약에 맞춰 식재료와 좌석을 준비합니다. 내용이 맞는지 확인해 주세요.",
  "rv.date2": "날짜", "rv.time2": "시간", "rv.guests2": "인원", "rv.course2": "코스",
  "rv.cxTitle": "취소 규정", "rv.cx48": "48시간 이내: 1인 ¥5,000", "rv.cx24": "24시간 이내: 1인 ¥10,000",
  "rv.cxTel": "급한 문의는 전화로", "rv.pvTitle": "개인정보 처리방침",
  "rv.pvBody": "제공해 주신 개인정보(이름, 이메일, 전화번호 등)는 예약 확인, 연락 및 매장 안내에만 사용됩니다. 법령에 따른 경우를 제외하고 제3자에게 제공하지 않습니다.",
  "rv.ck1": "날짜, 시간, 인원이 맞는지 확인했습니다.", "rv.ck2": "취소 규정을 읽고 동의합니다.",
  "rv.edit": "수정", "rv.send": "이 내용으로 보내기", "rv.sending": "전송 중…",
  "rv.eRequired": "필수 항목을 입력해 주세요.", "rv.ePast": "오늘 또는 이후 날짜를 선택해 주세요.",
  "rv.eSameday": "당일 예약은 전화로 접수합니다", "rv.ePassed": "오늘 이 시간대는 마감되었습니다. 다른 시간이나 날짜를 선택해 주세요.",
  "rv.eBlocked": "선택하신 날짜는 예약이 불가합니다. 다른 날짜를 선택해 주세요.", "rv.eCheck": "두 항목 모두 체크해 주세요.",
  "rv.eFull": "이 시간대는 만석입니다. 다른 시간을 선택해 주세요.",
  "rv.eNet": "예약 가능 여부를 확인하지 못했습니다. 통신 환경을 확인 후 다시 시도해 주세요.",
  "rv.eGeneric": "오류가 발생했습니다. 다시 시도해 주세요.",
  "rv.closedSlot": " (마감)", "rv.fullSlot": " (만석)"
};

const ID = {
  "hero.halal": "Pengalaman Omakase Halal", "hero.tour": "Perjalanan Kuliner Keliling Jepang",
  "theme.sushi": "Sushi", "theme.wagyu": "Wagyu",
  "menu.chefs": "Omakase Sang Chef",
  "menu.sushiH": "Kursus Omakase Sushi", "menu.wagyuH": "Kursus Omakase Wagyu",
  "menu.sushiP": "Sushi otentik, dibuat satu per satu dan disajikan ramah Muslim — perjalanan tenang menyusuri ikan terbaik musim ini.",
  "menu.wagyuP": "Wagyu premium & daging Kobe, disiapkan hidangan demi hidangan dan ramah Muslim — sukiyaki, steak, dan sushi wagyu.",
  "menu.follows": "Omakase kami mengikuti musim — bahan dapat berbeda.",
  "reserve.btnSushi": "Pesan Omakase Sushi Anda", "reserve.btnWagyu": "Pesan Omakase Wagyu Anda",
  "tag.popular": "Paling Populer",
  "nav.experience": "Pengalaman", "nav.menu": "Menu", "nav.story": "Kisah Kami",
  "nav.halal": "Ramah Muslim", "nav.access": "Lokasi", "nav.reserve": "Reservasi", "nav.interior": "Interior", "nav.performance": "Pertunjukan", "ui.slide": "Slide", "ui.googleReviews": "Ulasan Google", "ui.seeReviews": "Lihat ulasan di Google", "ui.outOf5": "dari 5",
  "ui.language": "Bahasa", "lang.h": "Bahasa", "lang.p": "Menu dan informasi sama dalam setiap bahasa.", "ui.viewMore": "Lihat selengkapnya", "ui.viewLess": "Tutup", "ui.close": "Tutup",
  "ui.menu": "Menu", "ui.reviews": "ulasan",
  "hero.h1a": "Perjalanan Kuliner", "hero.h1b": "KELILING JEPANG",
  "hero.sub": "Pengalaman Omakase Halal Sushi & Wagyu",
  "exp.label": "Pengalaman", "exp.h": "Perjalanan Menyusuri Jepang",
  "exp.p": "Perjalanan menyusuri budaya kuliner Jepang — wagyu, sushi, dan santapan dengan projection mapping. Omakase ramah Muslim, dirancang untuk pelancong dari seluruh dunia.",
  "exp.pm.h": "Kursus Sushi & Wagyu × Projection Mapping",
  "exp.pm.p": "Bukan sekadar makan — ini perjalanan menyusuri Jepang. Setiap hidangan disajikan bersama pengalaman projection mapping tentang budaya dan perjalanan Jepang, mengajak Anda menikmati budaya kuliner Jepang lewat hidangan istimewa (seluruhnya halal).",
  "menu.label": "Pilihan Kursus", "menu.h": "Pengalaman Kursus Omakase",
  "menu.note": "Seluruhnya ramah Muslim · Menu musiman", "menu.season": "* Bahan dapat berubah mengikuti musim.",
  "menu.premiumH": "\u201CSushi & Wagyu Indulgence\u201D",
  "menu.premiumP": "Di dalam kursus andalan kami terdapat pula hidangan premium — dibuat dari bahan musiman terbaik untuk pengalaman yang luar biasa.",
  "course.details": "Lihat detail", "course.reserve": "Pesan kursus ini", "course.incl": "termasuk pajak", "tag.lunch": "Khusus makan siang", "tag.recommended": "Rekomendasi",
  "story.label": "Kisah Kami", "story.h": "Kisah yang Dimulai pada 1962",
  "story.p1": "Generasi pertama memulai perjalanan ini sebagai pedagang Wagyu. Seorang perajin yang berhadapan langsung dengan sapi, menilai mutu daging, dan mengasah keahliannya. Sejak itu usaha keluarga berkembang ke grosir daging, toko daging, dan industri kuliner. Sebagai generasi kelima, saya tumbuh bersama daging.",
  "story.quote": "Bagi saya, Wagyu tidak pernah menjadi \u2018hidangan untuk acara istimewa\u2019. Saya sudah mengenal rasanya sejak kecil dan selalu dekat dengannya.",
  "story.by": "— Pemilik Generasi Kelima",
  "story.t.label": "Titik Balik",
  "story.t.p1": "Namun di usia 30-an, ketika saya berkunjung ke Amerika, perasaan itu terguncang. \u201CWAGYU\u201D yang saya temui di sana sama sekali berbeda dari Wagyu yang saya kenal. Sapi dari Australia dan Amerika beredar sebagai \u201CWagyu,\u201D dan banyak orang tersenyum sambil makan dan berkata, \u201CInikah Wagyu?\u201D",
  "story.t.p2": "Pemandangan itu membuat saya terkejut sekaligus kecewa. Sebagai generasi kelima, saya memutuskan untuk kembali menghadirkan \u201CWagyu sejati\u201D kepada dunia — dan membuka restoran ini di jantung Tokyo.",
  "story.q.label": "Komitmen Kami pada Mutu",
  "story.q.p": "Saya mengunjungi peternakan di seluruh Jepang dan hanya membeli Wagyu yang benar-benar saya setujui, per ekor utuh. Bukan Wagyu hasil penggemukan industri dengan lemak berlebih — melainkan Wagyu yang dibesarkan sehat, dengan umami dan kelembutan pada dagingnya sendiri, bukan hanya pada lemaknya. Filosofi ini mengalir ke setiap hidangan yang kami sajikan.",
  "story.w.label": "Untuk Semua Orang di Dunia",
  "story.w.p": "Saya sendiri yang memilih Wagyu yang diproses di pemasok tepercaya di Jepang. Restoran ini lahir untuk berbagi budaya kuliner Jepang yang otentik dengan semua orang — tanpa memandang kebangsaan, agama, usia, atau jenis kelamin.",
  "halal.label": "Santapan Ramah Muslim", "halal.h": "Pengalaman Bersantap Ramah Muslim di {city}",
  "halal.p1": "Selamat datang di restoran kami — ruang yang hangat dan inklusif tempat tamu dari segala budaya dapat bersantap dengan tenang. Kami menyiapkan hidangan tanpa babi dan tanpa alkohol dengan saksama, sehingga menjadi pilihan tepercaya bagi pelancong dan keluarga Muslim yang berkunjung ke Jepang.",
  "halal.p2": "Silakan sampaikan preferensi atau pantangan makanan Anda saat memesan — kami akan berusaha sebaik mungkin memenuhinya.",
  "badge.nopork": "Tanpa babi", "badge.noalc": "Tanpa alkohol dalam makanan", "badge.mf": "Ramah Muslim",
  "voices.label": "Suara Tamu", "voices.h": "Dari Seluruh Dunia", "voices.p": "Sebagian kesan yang dibagikan oleh tamu kami.",
  "access.label": "Lokasi", "access.h": "Temukan Kami", "access.name": "Restoran", "access.addr": "Alamat",
  "access.hours": "Jam buka", "access.open": "Buka", "access.tel": "Telepon",
  "access.stations": "Stasiun terdekat", "access.min": "menit", "access.maps": "Buka di Google Maps",
  "reserve.label": "Reservasi", "reserve.h": "Mulai Pengalaman Anda",
  "reserve.p": "Reservasi disarankan 2 minggu sebelumnya. Tamu tanpa reservasi kami terima sesuai ketersediaan.",
  "reserve.btn": "Pesan tempat duduk", "reserve.btnTc": "Pesan lewat TableCheck",
  "reserve.noteForm": "* Reservasi dikonfirmasi setelah email dari {brand}.",
  "reserve.noteTc": "* Reservasi ditangani TableCheck — aman & instan.",
  "reserve.notePhone": "* Reservasi hanya lewat telepon — silakan hubungi kami langsung.",
  "reserve.tel": "Ingin memesan lewat telepon?",
  "rv.eyebrow": "Reservasi", "rv.title": "Permintaan Reservasi",
  "rv.sub": "Reservasi dikonfirmasi setelah email dari {brand}.",
  "rv.s1": "Tanggal & waktu", "rv.s2": "Kursus", "rv.s3": "Data Anda",
  "rv.date": "Tanggal yang diinginkan", "rv.time": "Waktu", "rv.guests": "Jumlah tamu", "rv.course": "Kursus",
  "rv.coursePick": "Pilih kursus", "rv.courseHint": "Harga per orang. Seluruhnya ramah Muslim · Menu musiman.",
  "rv.name": "Nama", "rv.email": "Email", "rv.phone": "Telepon", "rv.ref": "Direkomendasikan oleh",
  "rv.optional": "Opsional", "rv.msg": "Permintaan khusus", "rv.msgPh": "Alergi, pantangan makanan, perayaan…",
  "rv.sameday": "Untuk hari ini? Hubungi kami", "rv.next": "Periksa & kirim",
  "rv.okTitle": "Permintaan diterima", "rv.okBody": "Mohon tunggu konfirmasi dari {brand}.",
  "rv.close": "Tutup", "rv.finalEyebrow": "Pemeriksaan akhir", "rv.finalTitle": "Mohon konfirmasi reservasi Anda",
  "rv.finalSub": "Kami menyiapkan bahan dan tempat duduk berdasarkan reservasi Anda. Mohon pastikan detailnya benar.",
  "rv.date2": "Tanggal", "rv.time2": "Waktu", "rv.guests2": "Tamu", "rv.course2": "Kursus",
  "rv.cxTitle": "Kebijakan Pembatalan", "rv.cx48": "Dalam 48 jam: ¥5.000 / orang", "rv.cx24": "Dalam 24 jam: ¥10.000 / orang",
  "rv.cxTel": "Untuk hal mendesak, hubungi kami di", "rv.pvTitle": "Kebijakan Privasi",
  "rv.pvBody": "Data pribadi yang Anda berikan (nama, email, nomor telepon, dll.) hanya digunakan untuk konfirmasi reservasi, komunikasi, dan pemberitahuan dari restoran. Kami tidak membagikannya kepada pihak ketiga kecuali diwajibkan hukum.",
  "rv.ck1": "Saya telah memastikan tanggal, waktu, dan jumlah tamu sudah benar.", "rv.ck2": "Saya telah membaca dan menyetujui kebijakan pembatalan.",
  "rv.edit": "Ubah", "rv.send": "Konfirmasi & kirim", "rv.sending": "Mengirim…",
  "rv.eRequired": "Mohon isi seluruh kolom wajib.", "rv.ePast": "Mohon pilih hari ini atau tanggal setelahnya.",
  "rv.eSameday": "Untuk reservasi hari ini, silakan hubungi kami", "rv.ePassed": "Waktu ini sudah lewat untuk hari ini. Mohon pilih waktu atau tanggal lain.",
  "rv.eBlocked": "Tanggal yang dipilih tidak tersedia. Mohon pilih tanggal lain.", "rv.eCheck": "Mohon centang kedua kotak.",
  "rv.eFull": "Waktu ini sudah penuh. Mohon pilih waktu lain.",
  "rv.eNet": "Ketersediaan tidak dapat diperiksa. Mohon periksa koneksi Anda dan coba lagi.",
  "rv.eGeneric": "Terjadi kesalahan. Mohon coba lagi.",
  "rv.closedSlot": " (tutup)", "rv.fullSlot": " (penuh)"
};

// 未翻訳キーは英語にフォールバック
[JA, ZHS, ZHT, KO, ID].forEach(d => {
  Object.keys(EN).forEach(k => { if (!(k in d)) d[k] = EN[k]; });
});

module.exports = {
  // 言語切替UIの並び。code は <html lang> に、font は動的読み込みする Google Fonts family。
  // 言語切替UI。ヘッダーのボタンには short、選択シートには label を出す。
  // font はその言語を選んだときだけ動的に読み込む Google Fonts family。
  langs: [
    { code: "en",  html: "en",      short: "English",  label: "English",           font: null },
    { code: "ja",  html: "ja",      short: "日本語",   label: "日本語",             font: "Zen+Old+Mincho:wght@400;600" },
    { code: "zhs", html: "zh-Hans", short: "简中",     label: "简体中文",           font: "Noto+Serif+SC:wght@400;600" },
    { code: "zht", html: "zh-Hant", short: "繁中",     label: "繁體中文",           font: "Noto+Serif+TC:wght@400;600" },
    { code: "ko",  html: "ko",      short: "한국어",   label: "한국어",             font: "Noto+Serif+KR:wght@400;600" },
    { code: "id",  html: "id",      short: "ID",       label: "Bahasa Indonesia",  font: null }
  ],
  dict: { en: EN, ja: JA, zhs: ZHS, zht: ZHT, ko: KO, id: ID }
};
